### ISSUE TITLE
The application crashes and exits by itself when clicking "CONTINUE AS GUEST"

### ISSUE THREAD

**Issue by ahyar92** [iPoli/iPoli-android#102]
#### Expected behavior
Supposedly, I can login through the "CONTINUE AS GUEST" feature without errors.

#### Actual behavior
When I try to login to the app via "CONTINUE AS GUEST", the app suddenly crashes and exits by itself.

#### How to reproduce
1. Install and open the app
2. Follow the steps when opening the app like adding "Username and Pet Name"
3. Once on the "My Amazing Day" page, please click the back button
4. Next, you will be on the login page. Then login through "CONTINUE AS GUEST". *Then you will find the error as I experienced.*

----
- Device: Xiaomi Redmi 4X
- Operating system: Marshmallow, 6.0.1 mmb29m (CPU: Octa-core Max 1.9 GHz, RAM: 2 GB)
- Application Version: 2.0.23

#### Recording Of The Bug
https://www.youtube.com/watch?v=Yn4vkjH1rLg

#### Logcat
```
--------- beginning of crash
05-17 23:15:08.097 12205 12271 E AndroidRuntime: FATAL EXCEPTION: ForkJoinPool.commonPool-worker-0
05-17 23:15:08.097 12205 12271 E AndroidRuntime: Process: io.ipoli.android, PID: 12205
05-17 23:15:08.097 12205 12271 E AndroidRuntime: java.lang.IllegalArgumentException: Failed requirement.
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at io.ipoli.android.player.auth.saga.AuthSideEffectHandler.updatePlayerAuthProvider(AuthSideEffectHandler.kt:143)
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at io.ipoli.android.player.auth.saga.AuthSideEffectHandler.doExecute(AuthSideEffectHandler.kt:73)
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at io.ipoli.android.common.AppSideEffectHandler.execute$suspendImpl(AppSideEffectHandler.kt:45)
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at io.ipoli.android.common.AppSideEffectHandler.execute(AppSideEffectHandler.kt)
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at io.ipoli.android.common.AppSideEffectHandler.execute(AppSideEffectHandler.kt:37)
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at io.ipoli.android.common.redux.CoroutineSideEffectHandlerExecutor$execute$1.doResume(StateStore.kt:47)
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1388)
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:251)
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:845)
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1674)
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1629)
05-17 23:15:08.097 12205 12271 E AndroidRuntime: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
05-17 23:15:08.126 12205 12271 E MQSEventManagerDelegate: failed to get MQSService.```

**Comment by curiousily** [comment]
Fixed in the latest version. Thanks!
