### ISSUE TITLE
Performing a "zoom" on the "My Amazing Day" feature will cause the Crash app.

### ISSUE THREAD

**Issue by rezamusic881** [iPoli/iPoli-android#104]
#### Expected behavior
Supposedly, doing a "zoom" on the "My Amazing Day" view does not cause the application to crash.

#### Actual behavior
When I managed to enter the name and name of my elephant, I went directly on "My Amazing Day Feature". Then I did "zoom" on the appearance. The application crashes automatically.

#### How to reproduce
1. Instal App [here]( https://play.google.com/store/apps/details?id=io.ipoli.android)
2. Run the app.
3. Fill in your elephant name and name field.
4. Once successful, you will be linked directly to "My Amazing Day" feature. Do a "zoom" on the feature view.
5. The application will crash

***
***

* Browser : Redmi Note 5A
* System Operating : 7.1.0 Nougat
* App Version : 2.1.1

#### Recording Of The Bug
https://youtu.be/zQsL1dyiRpw

***
***

#### Logcat
```
05-19 04:39:02.218 18273 18273 E AndroidRuntime: FATAL EXCEPTION: main
05-19 04:39:02.218 18273 18273 E AndroidRuntime: Process: io.ipoli.android, PID: 18273
05-19 04:39:02.218 18273 18273 E AndroidRuntime: kotlin.KotlinNullPointerException
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at io.ipoli.android.quest.schedule.calendar.dayview.view.widget.CalendarDayView.resizeCalendarEvents(CalendarDayView.kt:661)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at io.ipoli.android.quest.schedule.calendar.dayview.view.widget.CalendarDayView.resizeCalendar(CalendarDayView.kt:649)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at io.ipoli.android.quest.schedule.calendar.dayview.view.widget.CalendarDayView.access$resizeCalendar(CalendarDayView.kt:39)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at io.ipoli.android.quest.schedule.calendar.dayview.view.widget.CalendarDayView$setupFSM$19.invoke(CalendarDayView.kt:555)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at io.ipoli.android.quest.schedule.calendar.dayview.view.widget.CalendarDayView$setupFSM$19.invoke(CalendarDayView.kt:39)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at io.ipoli.android.quest.schedule.calendar.dayview.view.widget.CalendarDayView$FSM$transition$a$1.execute(CalendarDayView.kt:64)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at io.ipoli.android.quest.schedule.calendar.dayview.view.widget.CalendarDayView$FSM.fire(CalendarDayView.kt:80)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at io.ipoli.android.quest.schedule.calendar.dayview.view.widget.CalendarDayView$createScaleDetector$1.onScale(CalendarDayView.kt:283)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ScaleGestureDetector.onTouchEvent(ScaleGestureDetector.java:373)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at io.ipoli.android.quest.schedule.calendar.dayview.view.widget.CalendarDayView$listenForZoom$1.onTouch(CalendarDayView.kt:625)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:10032)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2628)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at io.ipoli.android.quest.schedule.calendar.dayview.view.widget.CalendarDayView.dispatchTouchEvent(CalendarDayView.kt:873)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:417)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3199)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
05-19 04:39:02.218 18273 18273 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:379)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:10258)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4501)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4366)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3906)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3959)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3925)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4052)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3933)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4109)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3906)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3959)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3925)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3933)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3906)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6310)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6284)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6245)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6416)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6384)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6439)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:688)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:617)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:754)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6361)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
05-19 04:39:02.219 18273 18273 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

#### Proof Of Work Done
[Submit in github](http://www.github.com/rezamusic881)

**Comment by curiousily** [comment]
Hey @rezamusic881,

The issue should be fixed in the latest version of the app. Please, write back if you encounter other issues.

Thanks for reporting this!

Regards
