### ISSUE TITLE
The application crashes when double-clicking on the pet rename feature

### ISSUE THREAD

**Issue by ahyar92** [iPoli/iPoli-android#110]
#### Expected behavior
Supposedly, when the user accidentally double-clicks on the pet rename feature, and then renames the pet, the app will not crash.

#### Actual behavior
Initially, when I entered the pet page and tried to rename the pet. And I accidentally double-clicked on the pet rename feature, because at the first click the rename page a little longer appears, and after I renamed the pet and clicked OK, the app suddenly crashes.

Then I tried to trace the error by doing the same thing, I tried double-clicking on the pet rename feature, then trying to add a new pet name, after clicking OK the application actually crashes and exit by itself.

#### How to reproduce
1. Install and sign in
2. After entering the application page, please click on the pet page
3. Next please double click on the pet rename feature (Pencil Icon)
4. Fill in the name of the latest pet, and click OK. *Then the application will crash and exit by itself.*

----
- Device: Xiaomi Redmi 4X
- Operating system: Marshmallow, 6.0.1 mmb29m (CPU: Octa-core Max 1.9 GHz, RAM: 2 GB)
- Application Version: 2.1.9

#### Recording Of The Bug
https://www.youtube.com/watch?v=vnjlPDbXJwI

#### Logcat
```
05-24 15:41:31.420 29774 29774 E AndroidRuntime: FATAL EXCEPTION: main
05-24 15:41:31.420 29774 29774 E AndroidRuntime: Process: io.ipoli.android, PID: 29774
05-24 15:41:31.420 29774 29774 E AndroidRuntime: java.lang.IllegalArgumentException: Key PetDialogViewState is already added to the state?!
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at io.ipoli.android.common.redux.StateStore$CompositeReducer.reduce(StateStore.kt:192)
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at io.ipoli.android.common.redux.StateStore.applyReducers(StateStore.kt:153)
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at io.ipoli.android.common.redux.StateStore.access$applyReducers(StateStore.kt:106)
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at io.ipoli.android.common.redux.StateStore$createStateActor$1.doResume(StateStore.kt:145)
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1388)
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:251)
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:845)
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1674)
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1629)
05-24 15:41:31.420 29774 29774 E AndroidRuntime: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
05-24 15:41:31.449 29774 29774 E MQSEventManagerDelegate: failed to get MQSService.
```

**Comment by curiousily** [comment]
Hey @ahyar92 ,

Thanks for showing so detailed reproduction of this issue! It should be fixed in the latest version of the app!

Cheers!
